[package]
name = "viper-encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
pest = "2.7.11"
pest_derive = "2.7.11"
sexpr_parser = "0.3.0"
strum = { version = "0.26.3", features = ["derive"] }
# viper = { path = "../prusti-dev/viper"}