name: Builds the Pancake Language Server

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install default tools
      run: sudo apt-get update && sudo apt-get install -y curl build-essential libssl-dev pkg-config unzip
    - name: Install JDK11
      run: sudo apt-get install -y openjdk-11-jdk

    - name: Set up cargo cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Export ENVS
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        export LD_LIBRARY_PATH=$JAVA_HOME/lib/server:$LD_LIBRARY_PATH

    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Download ViperTools
      run: |
        VERSION=$(cat viper-toolchain)
        OS="Linux"
        BASE_URL="https://github.com/viperproject/viper-ide/releases/download"
        ZIP_FILE="ViperTools${OS}.zip"
        ZIP_URL="${BASE_URL}/${VERSION}/${ZIP_FILE}"
        curl -LO $ZIP_URL
        UNZIP_DIR="viper"
        unzip -o $ZIP_FILE -d $UNZIP_DIR
        export VIPER_INSTALL=$(pwd)/$UNZIP_DIR
        echo "VIPER_INSTALL is set to ${VIPER_INSTALL}"
        export VIPER_HOME=$VIPER_INSTALL/backends
        export Z3_EXE=$VIPER_INSTALL/z3/bin/z3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
