name: Build Rust Application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      LD_LIBRARY_PATH: /usr/lib/jvm/java-11-openjdk-amd64/lib/server
      VIPER_INSTALL: ${{ github.workspace }}/ViperTools

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            build-essential \
            libssl-dev \
            pkg-config \
            unzip \
            openjdk-11-jdk

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download and extract ViperTools
        run: |
          curl -L -o ViperToolsLinux.zip https://github.com/viperproject/viper-ide/releases/download/v4.3.1/ViperToolsLinux.zip
          unzip -o ViperToolsLinux.zip -d ViperTools
          rm ViperToolsLinux.zip

      - name: Set VIPER_HOME and Z3_EXE environment variables
        run: |
          echo "VIPER_HOME=${VIPER_INSTALL}/backends" >> $GITHUB_ENV
          echo "Z3_EXE=${VIPER_INSTALL}/z3/bin/z3" >> $GITHUB_ENV

      - name: Build 
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
