name: Run tests

on:
  push:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      LD_LIBRARY_PATH: /usr/lib/jvm/java-11-openjdk-amd64/lib/server
      VIPER_INSTALL: ${{ github.workspace }}/ViperTools
      CAKE_ML_INSTALL: ${{ github.workspace }}/cake-x64-64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            build-essential \
            libssl-dev \
            pkg-config \
            unzip \
            openjdk-11-jdk

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download and extract ViperTools
        run: |
          curl -L -o ViperToolsLinux.zip "https://github.com/viperproject/viper-ide/releases/download/$(cat viper-toolchain)/ViperToolsLinux.zip"
          unzip -o ViperToolsLinux.zip -d ViperTools
          rm ViperToolsLinux.zip

      - name: Set VIPER_HOME and Z3_EXE environment variables
        run: |
          echo "VIPER_HOME=${VIPER_INSTALL}/backends" >> $GITHUB_ENV
          echo "Z3_EXE=${VIPER_INSTALL}/z3/bin/z3" >> $GITHUB_ENV
      
      - name: Download and extract CakeML
        run: |
          curl -L -o cake-x64-64.tar.gz "https://cakeml.org/regression/artefacts/$(cat cake-toolchain)/cake-x64-64.tar.gz"
          tar -xvzf cake-x64-64.tar.gz

      - name: Build CakeML compiler
        run: make -C cake-x64-64

      - name: Set CAKE_ML environment variables
        run: |
          echo "CAKE_ML=${CAKE_ML_INSTALL}/cake" >> $GITHUB_ENV

      - name: Run tests
        run: cargo test -p pancake2viper --release --verbose -- --test-threads=1
